### ISSUE TITLE
Footer Acquia issues

### ISSUE THREAD

**Issue by tompagabor** [drupalironcamp/static-2015#5]
From acquia site: (https://www.acquia.com/free-hosting-drupal-community-sites)

The footer section of each page needs to display:
 - the following text: “Drupal community hosting powered by Acquia Cloud”
 - and an Acquia logo (that we provide)

**Comment by zsofimajor** [comment]
You can get a logo from the bottom of this page: https://www.acquia.com/branding-requirements

**Comment by aboros** [comment]
hi guys, i used a different logo than that on the branding requirements page, but i think it's ok.  
screenshot: https://www.evernote.com/shard/s15/sh/a39d38f2-65b9-4207-8c3e-e0f0871ca2f6/fc762fd6ec09cd557779d3eb3f1c01fa
The code is sitting in this branch, please let me know if i can go ahead and create a pull request or need to change it in any way.

**Comment by segi** [comment]
It looks good! I give a +1 for it! :)
But, we are waiting for another feedback.

**Comment by tompagabor** [comment]
Thanks, great job! :)
I found this, about the logo usage:
http://acquiabrand.drupalgardens.com/logos-trademarks

So, your version is OK, i think.

Just one mention: maybe add equal space top and bottom of the logo. Now, the bottom space is a little bit smaller.

**Comment by aboros** [comment]
i grabbed the exact logo file from acquia.com header, so i think they will be ok with it.
both margins are 14px (1em) so mathematically equal, but maybe they should be optically equal, true dat. let me see what i can do about it.

**Comment by aboros** [comment]
here you go. normal line-height of p in footer caused the additional vertical space.
![drupal_iron_camp](https://cloud.githubusercontent.com/assets/359641/5778247/2a3da2e6-9d9a-11e4-8ed6-e7ed2fd199d0.png)

**Comment by zsofimajor** [comment]
Please add a URL to the logo: https://www.acquia.com/products-services/acquia-hosting

**Comment by tompagabor** [comment]
linked
